// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaC3seUX6eAoS86rjt1wnfOCm39sJhdY',
    appId: '1:1072819351681:web:ce2a305b1b4fb38a149d80',
    messagingSenderId: '1072819351681',
    projectId: 'todo-app-1b48c',
    authDomain: 'todo-app-1b48c.firebaseapp.com',
    databaseURL: 'https://todo-app-1b48c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-1b48c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0CFOldMRlOesj9gqTCxoxIimpM1AatI',
    appId: '1:1072819351681:android:a5417a1a31a64eba149d80',
    messagingSenderId: '1072819351681',
    projectId: 'todo-app-1b48c',
    databaseURL: 'https://todo-app-1b48c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-1b48c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQ5nf7S-WAZS306XBUe1dv0K8SM-uaQw',
    appId: '1:1072819351681:ios:3fb7e217337b237b149d80',
    messagingSenderId: '1072819351681',
    projectId: 'todo-app-1b48c',
    databaseURL: 'https://todo-app-1b48c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-1b48c.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQ5nf7S-WAZS306XBUe1dv0K8SM-uaQw',
    appId: '1:1072819351681:ios:8d79d8987d90a497149d80',
    messagingSenderId: '1072819351681',
    projectId: 'todo-app-1b48c',
    databaseURL: 'https://todo-app-1b48c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-1b48c.appspot.com',
    iosBundleId: 'com.example.ticTacToe.RunnerTests',
  );
}
